ifneq ($(filter m y,$(CONFIG_USE_MMI_CHARGER)),)
    ccflags-y += -DUSE_MMI_CHARGER
    ccflags-y += -I$(srctree)/$(src)/../mmi_charger
endif

ccflags-$(CONFIG_ADAPTIVE_TOLERANCE_OPTIMIZATION) += -DADAPTIVE_TOLERANCE_OPTIMIZATION

obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge.o
