ccflags-y += -I$(srctree)/include/linux/input/awinic

ccflags-$(CONFIG_AW96XX_POWER_SUPPLY_ONLINE) += -DCONFIG_USE_POWER_SUPPLY_ONLINE

awinic_sar-objs := comm/aw_sar_comm_interface.o aw_sar.o aw9610x/aw9610x.o aw9620x/aw9620x.o aw9620x/aw_update_fw.o aw963xx/aw963xx.o

obj-$(CONFIG_AW96XX_SAR) := awinic_sar.o
