obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI) := goodix_brl_mmi.o

goodix_brl_mmi-objs := \
					goodix_brl_i2c.o \
					goodix_brl_spi.o \
					goodix_ts_core.o \
					goodix_brl_hw.o \
					goodix_cfg_bin.o \
					goodix_ts_utils.o \
					goodix_brl_fwupdate.o \
					goodix_ts_inspect.o \
					goodix_ts_tools.o \
					goodix_ts_config.o

ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_SPI) += -DCONFIG_TOUCHSCREEN_GOODIX_BRL_SPI

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_FOD)),)
    ccflags-y += -DCONFIG_GTP_FOD
    goodix_brl_mmi-objs += goodix_ts_gesture_fod.o
else
    goodix_brl_mmi-objs += goodix_ts_gesture.o
endif

ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_LIMIT_USE_SUPPLIER) += -DCONFIG_GTP_LIMIT_USE_SUPPLIER
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_ENABLE_PM_QOS) += -DCONFIG_GTP_ENABLE_PM_QOS
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_ESD_ENABLE) += -DCONFIG_GOODIX_ESD_ENABLE
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_SAVE_IN_CSV) += -DGTP_SAVE_IN_CSV
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_LAST_TIME) += -DCONFIG_GTP_LAST_TIME

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_DDA_STYLUS)),)
    ccflags-y += -DCONFIG_GTP_DDA_STYLUS
    goodix_brl_mmi-objs += goodix_ts_dda.o
endif

ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_DDA_PASSIVE_STYLUS) += -DCONFIG_MOTO_DDA_PASSIVESTYLUS

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    goodix_brl_mmi-objs += goodix_ts_mmi.o
endif

ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_ENABLE_PALM) += -DGOODIX_PALM_SENSOR_EN
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_PALM_CANCEL) += -DCONFIG_ENABLE_GTP_PALM_CANCEL
ccflags-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_MMI_PASSIVE_PEN_NOTIFIER) += -DGTP_PEN_NOTIFIER

ccflags-$(CONFIG_MIAMI_DTB) += -DPRODUCT_MIAMI
ccflags-$(CONFIG_BANGKK_DTB) += -DPRODUCT_BANGKK
